-- set telescope fuzzy find shortcuts
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<c-p>', builtin.git_files, {})
vim.keymap.set('n', '<c-t>', builtin.find_files, {})
vim.keymap.set('n', '<c-w>', builtin.grep_string, {})
vim.keymap.set('n', '<c-f>', builtin.live_grep, {})

vim.keymap.set('n', 'gr', builtin.lsp_references)
vim.keymap.set('n', 'gD', builtin.lsp_definitions)
vim.keymap.set('n', 'gW', builtin.lsp_workspace_symbols)
vim.keymap.set('n', 'g0', builtin.lsp_document_symbols)
vim.keymap.set('n', 'ge', builtin.diagnostics)
vim.keymap.set('n', 'gi', builtin.lsp_implementations)
vim.keymap.set('n', 'gtd', builtin.lsp_type_definitions)
vim.keymap.set('n', 'gd', builtin.lsp_definitions)
vim.keymap.set('n', 'ga', '<cmd> lua vim.lsp.buf.code_action()<CR>', { silent = true })
